### ISSUE TITLE
add data-table component to list bookings

### ISSUE THREAD

**Issue by fulls1z3** [prime-travel/public-docs#1]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**User story**
As a **user**
I want to click on `Bookings -> Hotel bookings` on the left navigation
so that I can navigate to `/bookings/hotel-bookings` and see the list of bookings

**Acceptance criteria**
* **AC.1:** The data-table must display the columns specified at the task **T2**.
* **AC.2:** The data-table must display the **most recent** bookings first by default.
* **AC.3:** Pagination must work - displaying `20` items per pages by default.
* **AC.4:** Each row on the data-table must have the following action buttons: `View` and `Edit`.
* **AC.5:** When user clicks on Refresh button table and contents should be reloaded and displayed returned results.
* **AC.6:** Clicking on `View` button must navigate to the hotel booking overview page.
* **AC.7:** Clicking on `Edit` button must navigate to the hotel booking detail page (using ViewMode.Edit).
* ~~**AC.8:** Clicking on `Create a hotel booking` button must navigate to the hotel booking detail page (using ViewMode.Create).~~
* **AC.9:** Clicking on `Refresh` button must reload the contents of the data-table.

**Definition of done**
* Implements every task at the **Tasks** section
* Source code aligns with the [Coding standards](../wiki/Coding-standards)
* Has at least `1` approval review from code owners
* ~~Provides unit test coverage 100% of the code~~
* ~~100% test automation pass rate~~
* ~~Well-documented~~

**Tasks**
**T.1:** See [Navigation](../wiki/Navigation) for blueprints.
* [ ] The following navigation items must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__MODULE_I18N_KEY__`** = `BOOKING`
* **`__ICON_NAME__`** = `event`
* **`__MODULE_PATH__`** = **undefined**
* **`__MODULE_POSITION__`** = 3

`__TYPE_NAME__` | `__FEATURE_PATH__` | `__ITEM_POSITION__`
--- | --- | ---
HOTEL_BOOKING | `/bookings/hotel-bookings` | 1

###### Note
On line 60, there's an existing navigation item beginning with the statement. `const reservations ...`. The implementation must occur by overwriting/replacing that navigation item - by renaming the `reservations` variable to `booking`, replacing the existing hierarchical child(ren) and further by following instructions above.

Also, replace the I18N entries above with the items on line 17 & 18 located at the language resource files.

**T.2:** See [Adding a master component (master/overview pattern)](../wiki/Adding-a-master-component-(master-overview-pattern)) for blueprints.
* [ ] The following directory & file structure must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`

* [ ] The following routes must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`
* **`__FEATURE_PATH__`** = `hotel-bookings`

* [ ] The following configuration must be provided.
* **`__API_NAME__`** = `todos`
* **`__ENDPOINT_NAME__`** = `some-todos`

* [ ] The following service and/or methods must be provided.
* **`__API_NAME__`** = `bookings`
* **`__API_ENDPOINT__`** = `hotel-bookings`
* **`__TYPE_NAME__`** = `hotel-booking`

* [ ] The following module must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`

* [ ] Application routes must be provided.

* [ ] Unit tests must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`

* [ ] Component (view) must be provided.

* [ ] Component (stylesheets) must be provided.

* [ ] Component (code) must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__MODULE_PATH__`** = `bookings`
* **`__TYPE_NAME__`** = `hotel-booking`
* **`__FEATURE_PATH__`** = `hotel-bookings`
* **`__FIELD_NAMES__`** = `code,vendor.name,supplier.name,saleAtUtc,checkInAtUtc,checkOutAtUtc,guests,totalPrice`
* **`__ICON_NAME__`** = `event`

Placement | `__I18N_KEY__` | `__I18N_VALUE__` (en) | `__I18N_VALUE__` (tr)
--- | --- | --- | ---
Append after 520 | PAGE_TITLE | Hotel bookings | Otel rezervasyonları
... | HOTEL_BOOKING_TABLE.TITLE | Hotel bookings | Otel rezervasyonları
... | HOTEL_BOOKING_TABLE.CREATE.TOOLTIP | Create a new hotel booking | Yeni bir otel rezervasyonu oluştur
... | HOTEL_BOOKING_TABLE.CODE_COL_TITLE | Code | Kod
... | HOTEL_BOOKING_TABLE.NAME_COL_TITLE | Name | Adı
... | HOTEL_BOOKING_TABLE.CODE_COL_TITLE | Booking code | Rezervasyon kodu
... | HOTEL_BOOKING_TABLE.VENDOR_COL_TITLE | TO name | TO adı
... | HOTEL_BOOKING_TABLE.SUPPLIER_COL_TITLE | Hotel name | Otel adı
... | HOTEL_BOOKING_TABLE.BOOKING_AT_UTC_COL_TITLE | Booking date | Rezervasyon tarihi
... | HOTEL_BOOKING_TABLE.CHECK_IN_AT_UTC_COL_TITLE | Check-in date | Check-in tarihi
... | HOTEL_BOOKING_TABLE.CHECK_OUT_AT_UTC | Nights | Check-out date | Check-out tarihi
... | HOTEL_BOOKING.HOTEL_BOOKINGS_TABLE.GUESTS_COL_TITLE | Pax | Pax
... | HOTEL_BOOKING.HOTEL_BOOKINGS_TABLE.PRICE_COL_TITLE | Price | Fiyat

**T.3:** **index.component.ts** (*customization*)
* [ ] `dao` must be initialized with the following arguments (*custom query params*).
```TypeScript
this.dao = new DataTableDao(this.service, 'getHotelBookings$', [
  {
    key: 'fields',
    value: 'code,vendor.name,supplier.name,saleAtUtc,checkInAtUtc,checkOutAtUtc,guests,totalPrice'
  },
  {
    key: 'populate',
    value: 'vendor,supplier'
  },
  {
    key: 'sort',
    value: '-createdAtUtc'
  }
]);
```

* [ ] Initialization of `cols` must be **prepended** to the scope of `switchMap` call of `this.route.data` object, and columns with property references `guests` and `totalPrice` must have a callback to project computed data.

```TypeScript
this.cols = [
  // previous elements

  columnFactory('guests[0].type', 'PUBLIC.BOOKINGS.HOTEL_BOOKINGS.HOTEL_BOOKINGS_TABLE.GUESTS_COL_TITLE', cur => {
    const res = ...
    // iterate through the `cur` array as follows
    // const adult = cur.filter(guest => guest.occupancyType === OccupancyTypeAdult);
    // const child = cur.filter(guest => guest.occupanctType === OccupanctType.Child)
    //   .map(guest => ({birthDate: guest.birthDate, age: guest.age}));
    // const infant = cur.filter(guest => guest.occupanctType === OccupanctType.Infant)
    //   .map(guest => ({birthDate: guest.birthDate, age: guest.age}));

    // and return the guests in the string format:
    // if there're no child/infant: `${a}`, where `a` is the length of the array `adult`
    // if there's any child/infant: `${a}, ${c + i}(${x})` where `a` is the length of the array `adult`
    // and `c` is the length of the array `child` and `i` is the length of the array `child`
    // and `x` is the string representation of `ages` of each child/infant separated by `+` sign
    // ex: `2, 3 (12+6+1)` means 2 adults 3 kids with ages 12, 6 and 1

    // for calculating dates, prefer importing moment and using its methods

    return res;
  })).

  // next elements
];
```
