### ISSUE TITLE
add component to have booking overview

### ISSUE THREAD

**Issue by fulls1z3** [prime-travel/public-docs#2]
**I'm submitting a ...**  (check one with "x")
```
[ ] Regression (a behavior that used to work and stopped working in a new release)
[ ] Bug report  <!-- Please check the repository for a similar issue or PR before submitting -->
[x] Feature request
[ ] Documentation issue or request
```

**User story**
As a **user**
I want to click on `View` action button on **Bookings list**
so that I can navigate to `/bookings/hotel-bookings/{{id}}` and see the booking overview

**Acceptance criteria**
* **AC.1:** The overview must display the members specified at the task **T2**.
* **AC.2:** Clicking on `Back` button must navigate to the hotel bookings data-table page.

**Definition of done**
* Implements every task at the **Tasks** section
* Source code aligns with the [Coding standards](../wiki/Coding-standards)
* Has at least `1` approval review from code owners
* ~~Provides unit test coverage 100% of the code~~
* ~~100% test automation pass rate~~
* ~~Well-documented~~

**Tasks**
**T.1:** See [Adding a master component (master/overview pattern)](../wiki/Adding-an-overview-component-(master-overview-pattern)) for blueprints.

* [ ] The following directory & file structure must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`
* **`__FEATURE_NAME__`** = `booking`

* [ ] The following routes must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`
* **`__FEATURE_NAME__`** = `booking`
* **`__FEATURE_PATH__`** = `hotel-bookings`

* [ ] The following service and/or methods must be provided.
* **`__API_NAME__`** = `bookings`
* **`__API_ENDPOINT__`** = `hotel-bookings`
* **`__TYPE_NAME__`** = `hotel-booking`

* [ ] The following module must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`
* **`__FEATURE_NAME__`** = `booking`

* [ ] Unit tests must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__TYPE_NAME__`** = `hotel-booking`
* **`__FEATURE_NAME__`** = `booking`

* [ ] Component (view) must be provided.
* **`__MODULE_NAME__`** = `booking`
* **`__FEATURE_NAME__`** = `booking`

* [ ] Component (stylesheets) must be provided.
* **`__FEATURE_NAME__`** = `booking`

* [ ] Component (code) must be provided.
* **`__TYPE_NAME__`** = `hotel-booking`
* **`__FEATURE_NAME__`** = `booking`
* **`__ICON_NAME__`** = `event`

Placement | `__I18N_KEY__` | `__I18N_VALUE__` (en) | `__I18N_VALUE__` (tr)
--- | --- | --- | ---
Append after **master** component | PAGE_TITLE | Hotel booking overview | Otel rezervasyonu bilgileri

**T.2:** **booking-overview.component.ts** (*customization*)
Full object representation is available at the [API documentation](https://api.docs.holidaylab.net/#4584b169-7363-4534-24a5-f156cbba50cd).

* [ ] The first tab at the overview must have label `TAB_DETAILS`.

* [ ] The `TAB_DETAILS` must have following members of the `booking` object.
  * `code`
  * first element of `references` of type `ReferenceType.Voucher`
  * first element of `references` of type `ReferenceType.Hub`
  * `vendor.code`, `vendor.name` (*see [object representation](https://api.docs.holidaylab.net/#8f92db23-c541-97f9-d490-39af03d9b049)*)
  * `market.code`, `market.name` (*see [object representation](https://api.docs.holidaylab.net/#50f6b843-088d-4679-b12b-9dd90923e8c0)*)
  * `supplier.code`, `supplier.name` (*see [object representation](https://api.docs.holidaylab.net/#acf765e8-cd35-46da-880b-7778eaa0edfd)*)
  * `saleAtUtc`
  * `checkInAtUtc`, `checkOutAtUtc`
  * Table of `guests`, with columns
      * `type`
      * `gender`
      * `age` (*if exists calculate using `birthDate`, if not bump `age`*)
      * `nationality`
  * `contract.code`, `chargePlan.code`
  * Table of `priceBreakdown`, with columns
      * `date`
      * `amount` + `currency.code`
      * `boardCharges` + `boardChargeAmount` + `currency.code` (*map the `code` property from array `boardCharges`*)  (*see [object representation](https://api.docs.holidaylab.net/#67eaf8d8-0e9a-4292-b4f3-00ba05e225be)*)
      * `occupancyCharges` + `occupancyChargeAmount` + `currency.code` (*map the `code` property from array `occupancyCharges`*)  (*see [object representation](https://api.docs.holidaylab.net/#5b9254d8-7503-4286-9a47-eb9dccd0001d)*)
      * `services` + `serviceChargeAmount` + `currency.code` (*map the `code` property from array `services`*)  (*see [object representation](https://api.docs.holidaylab.net/#ae7e472b-0df9-4e34-96b2-1374622e5da6)*)
      * `discounts` + `discountAmount` + `currency.code` (*map the `code` property from array `discounts`*)  (*see [object representation](https://api.docs.holidaylab.net/#ae7e472b-0df9-4e34-96b2-1374622e5da6)*)
    * `totalPrice` + `currency.code`
    * Table of `cancellationTerms` (*see [object representation](https://api.docs.holidaylab.net/#8995b452-3b20-45a6-877f-68a3ba101944)*), with columns
      * `strategy`
      * first element of `grades`, bump `offset`
      * first element of `grades`, bump `percent`
    * Table of `fees` (*see [object representation](https://api.docs.holidaylab.net/#0f675a88-1d57-4034-8fe9-edff26613ea5)*), with columns
      * `type`
      * `strategy`
      * `isPerPax`
      * `interval`
      * first element of `grades`, bump `amount` or `percent` (*chose the one not having null value*)
    * `comments`

* [ ] The following I18N table will apply
Placement | `__I18N_KEY__` | `__I18N_VALUE__` (en) | `__I18N_VALUE__` (tr)
--- | --- | --- | ---
Append after *PAGE_TITLE* | TAB_DETAILS | Booking details | Rezervasyon detayları

For the object representation above, keys must be defined from `camelCase` to `UPPER_CASE`, with below the scope `PUBLIC.BOOKING.HOTEL_BOOKING_OVERVIEW.TAB_DETAILS`.

Example: `vendor` => `PUBLIC.BOOKING.HOTEL_BOOKING_OVERVIEW.TAB_DETAILS.VENDOR`.
